<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Teller.aspx.cs" Inherits="Bank_Management.Teller" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>EveryThing 4 You</title>
    <link href="ViewCustomer.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <div>
                <br />
             <asp:TextBox ID="TextBox1" CssClass="txt1 txtstyle" placeholder="ID" runat="server" Height="16px" Width="216px"></asp:TextBox>
              <br />   
                 <br />
             <asp:TextBox ID="TextBox2" CssClass="txt1 txtstyle" placeholder="Anything" runat="server" Height="16px" Width="216px"></asp:TextBox>
              <br />
            <asp:Button ID="Button1" CssClass="btn1 btnstyle" runat="server" Text="Collect Money" OnClick="Button1_Click" />
             <asp:Button ID="Button2" CssClass="btn2 btnstyle" runat="server" Text="Open Account" OnClick="Button2_Click" />
             <asp:Button ID="Button3" CssClass="btn2 btnstyle" runat="server" Text="Closed Account" OnClick="Button3_Click" />
            
             <asp:Button ID="Button4" CssClass="btn2 btnstyle" runat="server" Text="Loan Request" OnClick="Button4_Click" />
             <asp:Button ID="Button5" CssClass="btn2 btnstyle" runat="server" Text="Information" OnClick="Button5_Click" />   
             <asp:Button ID="Button6" CssClass="btn2 btnstyle" runat="server" Text="Issue Card" OnClick="Button6_Click" />
             <asp:Button ID="Button7" CssClass="btn2 btnstyle" runat="server" Text="All Records" OnClick="Button7_Click" />  <br /><br /><br /><br />

        </div>
        </div>
        
        <asp:GridView ID="GridView1" runat="server" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGeneratedColumn="false" AlternatingRowStyle-BorderStyle="Double" BackColor="#DEBA84" BorderColor="#DEBA84" RowStyle-ForeColor="Orchid" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2">
<AlternatingRowStyle BorderStyle="Double"></AlternatingRowStyle>

            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />

<RowStyle ForeColor="#8C4510" BackColor="#FFF7E7"></RowStyle>
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FFF1D4" />
            <SortedAscendingHeaderStyle BackColor="#B95C30" />
            <SortedDescendingCellStyle BackColor="#F1E5CE" />
            <SortedDescendingHeaderStyle BackColor="#93451F" />
        </asp:GridView>
    </form>
</body>
</html>
